server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lets-trip-db2.c2zrdenz9vsq.us-east-1.rds.amazonaws.com:3306/community
    username: letstrip
    password: letstrip


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        dialect: org.hibernate.dialect.MariaDB103Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info