server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lets-trip-db.cprq7tgal4rf.us-east-1.rds.amazonaws.com:3306/community
    username: letstrip
    password: qwer1234


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
#        dialect: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info