spring:
  datasource:
    url: jdbc:mysql:lets-trip-db.cprq7tgal4rf.us-east-1.rds.amazonaws.com:3306/community
    username: letstrip
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
